/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChauffeurRouteImport } from './routes/chauffeur'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuiviIdRouteImport } from './routes/suivi.$id'
import { Route as ReservationIdRouteImport } from './routes/reservation.$id'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicNotifyReservationRouteImport } from './routes/api/public/notify-reservation'
import { Route as ApiPublicDriverLocationRouteImport } from './routes/api/public/driver-location'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationRoute = ReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChauffeurRoute = ChauffeurRouteImport.update({
  id: '/chauffeur',
  path: '/chauffeur',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviIdRoute = SuiviIdRouteImport.update({
  id: '/suivi/$id',
  path: '/suivi/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationIdRoute = ReservationIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReservationRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyReservationRoute =
  ApiPublicNotifyReservationRouteImport.update({
    id: '/api/public/notify-reservation',
    path: '/api/public/notify-reservation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDriverLocationRoute = ApiPublicDriverLocationRouteImport.update({
  id: '/api/public/driver-location',
  path: '/api/public/driver-location',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/chauffeur': typeof ChauffeurRoute
  '/contact': typeof ContactRoute
  '/reservation': typeof ReservationRouteWithChildren
  '/services': typeof ServicesRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/reservation/$id': typeof ReservationIdRoute
  '/suivi/$id': typeof SuiviIdRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/driver-location': typeof ApiPublicDriverLocationRoute
  '/api/public/notify-reservation': typeof ApiPublicNotifyReservationRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/chauffeur': typeof ChauffeurRoute
  '/contact': typeof ContactRoute
  '/reservation': typeof ReservationRouteWithChildren
  '/services': typeof ServicesRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/reservation/$id': typeof ReservationIdRoute
  '/suivi/$id': typeof SuiviIdRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/driver-location': typeof ApiPublicDriverLocationRoute
  '/api/public/notify-reservation': typeof ApiPublicNotifyReservationRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/chauffeur': typeof ChauffeurRoute
  '/contact': typeof ContactRoute
  '/reservation': typeof ReservationRouteWithChildren
  '/services': typeof ServicesRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/reservation/$id': typeof ReservationIdRoute
  '/suivi/$id': typeof SuiviIdRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/driver-location': typeof ApiPublicDriverLocationRoute
  '/api/public/notify-reservation': typeof ApiPublicNotifyReservationRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/chauffeur'
    | '/contact'
    | '/reservation'
    | '/services'
    | '/email/unsubscribe'
    | '/reservation/$id'
    | '/suivi/$id'
    | '/api/public/contact'
    | '/api/public/driver-location'
    | '/api/public/notify-reservation'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/chauffeur'
    | '/contact'
    | '/reservation'
    | '/services'
    | '/email/unsubscribe'
    | '/reservation/$id'
    | '/suivi/$id'
    | '/api/public/contact'
    | '/api/public/driver-location'
    | '/api/public/notify-reservation'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/chauffeur'
    | '/contact'
    | '/reservation'
    | '/services'
    | '/email/unsubscribe'
    | '/reservation/$id'
    | '/suivi/$id'
    | '/api/public/contact'
    | '/api/public/driver-location'
    | '/api/public/notify-reservation'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ChauffeurRoute: typeof ChauffeurRoute
  ContactRoute: typeof ContactRoute
  ReservationRoute: typeof ReservationRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  SuiviIdRoute: typeof SuiviIdRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicDriverLocationRoute: typeof ApiPublicDriverLocationRoute
  ApiPublicNotifyReservationRoute: typeof ApiPublicNotifyReservationRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chauffeur': {
      id: '/chauffeur'
      path: '/chauffeur'
      fullPath: '/chauffeur'
      preLoaderRoute: typeof ChauffeurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi/$id': {
      id: '/suivi/$id'
      path: '/suivi/$id'
      fullPath: '/suivi/$id'
      preLoaderRoute: typeof SuiviIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation/$id': {
      id: '/reservation/$id'
      path: '/$id'
      fullPath: '/reservation/$id'
      preLoaderRoute: typeof ReservationIdRouteImport
      parentRoute: typeof ReservationRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-reservation': {
      id: '/api/public/notify-reservation'
      path: '/api/public/notify-reservation'
      fullPath: '/api/public/notify-reservation'
      preLoaderRoute: typeof ApiPublicNotifyReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/driver-location': {
      id: '/api/public/driver-location'
      path: '/api/public/driver-location'
      fullPath: '/api/public/driver-location'
      preLoaderRoute: typeof ApiPublicDriverLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReservationRouteChildren {
  ReservationIdRoute: typeof ReservationIdRoute
}

const ReservationRouteChildren: ReservationRouteChildren = {
  ReservationIdRoute: ReservationIdRoute,
}

const ReservationRouteWithChildren = ReservationRoute._addFileChildren(
  ReservationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ChauffeurRoute: ChauffeurRoute,
  ContactRoute: ContactRoute,
  ReservationRoute: ReservationRouteWithChildren,
  ServicesRoute: ServicesRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  SuiviIdRoute: SuiviIdRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicDriverLocationRoute: ApiPublicDriverLocationRoute,
  ApiPublicNotifyReservationRoute: ApiPublicNotifyReservationRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
