// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

export const requireSupabaseAuth = async ({ next }: any) => {
  return next({
    context: {
      supabase: null,
      userId: null,
      claims: null,
    },
  });
};
